package com.cbu.mobileapplicationproject.ui.base;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.cbu.mobileapplicationproject.Comment;
import com.cbu.mobileapplicationproject.CommentRecyclerAdapter;
import com.cbu.mobileapplicationproject.R;
import com.cbu.mobileapplicationproject.databinding.ActivityCommentBinding;

import java.util.ArrayList;


public class CommentActivity extends AppCompatActivity {
    private ArrayList<Comment> comments;
    private RecyclerView recyclerView;
    private CommentRecyclerAdapter commentRecyclerAdapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ActivityCommentBinding viewBinding = ActivityCommentBinding.inflate(getLayoutInflater());
        setContentView(viewBinding.getRoot());

        viewSettingsC();
        fillTheArrayC();
        commentRecyclerAdapter.notifyDataSetChanged();
    }

    private void fillTheArrayC(){

        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));
        comments.add(new Comment(R.drawable.profile_icon,"Ömer Özoğlu","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at imperdiet. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Arcu felis bibendum ut tristique et. Facilisis magna etiam tempor orci eu lobortis. Facilisis mauris sit amet massa vitae. Cursus sit amet dictum sit. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Mauris sit amet massa vitae tortor condimentum lacinia. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sagittis vitae et leo duis."));

    }
    private void viewSettingsC(){
        recyclerView = findViewById(R.id.recyclerview_comment);
        comments = new ArrayList<>();
        commentRecyclerAdapter = new CommentRecyclerAdapter(comments);
        recyclerView.setAdapter(commentRecyclerAdapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
    }

}